### ISSUE TITLE
Implement tooltips

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#164]
To clarify some features of the program, like what the different toggle buttons in settings do.
As discussed in #161

## Todo:
- [x] Settings
   - [x] Fragment dragging -> Disallow fragments being moved using mouse dragging
   - [ ] Fragment gradient -> [Insert tooltip]
   - [x] Frag. headers -> Show fragment headers that include data about the fragment
   - [x] Frag. line names -> Show the name or number of each fragment line
   - [x] Auto scroll to linked fragments -> Automatically scrolls linked fragments into view if possible
- [ ] ?

**Comment by Ycreak** [comment]
Shall we implement them with a little question mark icon like Naturalis Bioportal? See `https://bioportal.naturalis.nl/`, Advanced, in the input fields.

**Comment by sajvanwijk** [comment]
That could work. I'd prefer tooltips that maybe change your cursor into a cursor with a questionmark to show that a tooltip is there. Keeps the UI clean. But that obviously won't work on tablets.

**Comment by Ycreak** [comment]
Aye. A simple mouse over could be nice, but also not tablet friendly. Maybe we can underline the text to show the user something is clickable and then show the tooltip on hoover/click? So the text _Fragment dragging_ would be underlined.

**Comment by sajvanwijk** [comment]
Hmm, underline zou ik wel echt exclusief voor hyperlinks houden. Mss een combinatie van de eerste 2 ideeën? Dus knop + tooltip?

**Comment by Ycreak** [comment]
Je kunt altijd een proof of concept maken die we dan weer kunnen tonen :)

**Comment by sajvanwijk** [comment]
Will do

**Comment by sajvanwijk** [comment]
Resolved via PR #170
